#!/usr/bin/python


from video_capture import Capture
from frame_writer import FrameWriter
from ui import UI
import cv2
import basic_cam_setting
import numpy as np

cap = Capture()
cap.start()
ui = UI(cap)

brightness_ui = basic_cam_setting.BrightnessSetting(cap)
contrast_ui = basic_cam_setting.ContrastSetting(cap)
saturation_ui = basic_cam_setting.SaturationSetting(cap)
hue_ui = basic_cam_setting.HueSetting(cap)
fw = FrameWriter()

ui.add_ui(brightness_ui)
ui.add_ui(contrast_ui)
ui.add_ui(saturation_ui)
ui.add_ui(hue_ui)
ui.add_ui(fw)

ui_frame = None



while ui.keep_running():
    frame = cap.get_frame()

    if (frame == None):
	print "Failed to capture frame - check device."
	break;
	

    if (ui_frame == None):
        ui_frame = np.zeros(frame.shape, np.uint8)
    
    if ui.check_keys() > -1:
        ui_frame = np.zeros(frame.shape, np.uint8)
        ui.draw(ui_frame)

    frame = fw.process(frame)

    cv2.imshow('cosmos', cv2.bitwise_xor(frame, ui_frame))




cap.end()
cv2.destroyAllWindows()
